name: ci-app-go
on:
  pull_request:
    branches:
      - develop
jobs:
  check-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20", "1.15"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}
      - run: go test
      - run: go run main.go
